### ISSUE TITLE
Elasticache Redis Multi AZ not enabled

### ISSUE THREAD

**Issue by aibitayo55555** [UKHomeOffice/acp-tf-redis#8]
It was discovered that after enabling automatic failover Multi-AZ is not enabled. 
There is an open PR to fix this [here](https://github.com/hashicorp/terraform-provider-aws/pull/13909).
In the meantime, an immediate fix is to enable this locally after creating the Redis resource via terraform.

**Comment by tasharnvb** [comment]
Fixed by #9
